# Diferencia entre np.matrix y np.ndarray

En numpy hay varias formas de crear arreglos multidimensionales entre ellos contamos con np.array, np.ndarray, np.matrix, etc. En este documento veremos la diferencia entre np.matrix y np.ndarray.

> La diferencia más importante es que con np.matrix solo se pueden crear arreglos específicamente de rango 2, mientras que np.ndarray son arreglos multidimensionales, es decir, se pueden crear arreglos de cualquier rango con este tipo de estructura.

Veamos un ejemplo:

In [4]:
import numpy as np #Primero importamos numpy

Ahora creamos una matriz con np.matrix (Nótese que la matriz recibe un array de dos dimensiones)

In [35]:
matriz = np.matrix([[2,3],[3,2]])
matriz

matrix([[2, 3],
        [3, 2]])

Pasamos el mismo array a np.ndarray

In [36]:
ndarr = np.array([[2,3],[3,2]]) #al usar el método array en realidad nos devuelve un objeto de tipo ndarray
print(type(ndarr))
ndarr

<class 'numpy.ndarray'>


array([[2, 3],
       [3, 2]])

Hasta el momento todo bien, pero qué pasa si deseamos hacer un cubo

In [37]:
ndarr = np.array([[[2,3],[3,2]],[[3,1],[1,1]]])
ndarr.shape

(2, 2, 2)

No hay ningún problema con ndarray, cómo se puede observar en el output tiene rango 3... pero ¿Qué pasa si queremos pasarle lo mismo a matrix?

In [38]:
matriz = np.matrix([[[2,3],[3,2]],[[3,1],[1,1]]])
matriz.shape

ValueError: matrix must be 2-dimensional

Numpy nos devuelve un error bastante específico **matrix must be 2-dimensional** es decir, numpy nos dice que por obligación matrix tiene que ser de rango 2.

Además si vamos a la documentación oficial para cada estructura de datos, podemos darnos cuenta que sus operaciones son bastante diferentes.

**Documentación ndarray:** https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html

**Documentación matrix:** https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html


En la documentación de ndarray se pueden encontrar métodos más genericos o generales, tales cómo sort, argmax, min, resize, etc.

Mientras que en la documentación de Matrix además de encontrar los métodos anteriormente mencionados se encuentran métodos bastante específicos para matrices, tales cómo: 

* getA: returna la matriz cómo ndarray
* getA1: retorna la matriz cómo ndarray aplanado
* getH: retorna la matriz conjugada
* getI: retorna la matriz con su multiplicativo inverso
* getT: retorna la matriz transpuesta

Además la manera de multiplicarse es diferente, veamos primero con ndarray

In [41]:
ndarr = np.array([[2,3],[3,2]])
ndarr*ndarr

array([[4, 9],
       [9, 4]])

In [42]:
matriz = np.matrix([[2,3],[3,2]])
matriz*matriz

matrix([[13, 12],
        [12, 13]])

Si nos damos cuenta los resultados de la multiplicación son diferentes, en el ndarray nos da la multiplicación elemento por elemento, mientras que con matrix nos da la multiplicación matricial.